/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing ExtensionsV1beta1ScaleSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtensionsV1beta1ScaleSpecTests
    {
        // TODO uncomment below to declare an instance variable for ExtensionsV1beta1ScaleSpec
        //private ExtensionsV1beta1ScaleSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtensionsV1beta1ScaleSpec
            //instance = new ExtensionsV1beta1ScaleSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtensionsV1beta1ScaleSpec
        /// </summary>
        [Test]
        public void ExtensionsV1beta1ScaleSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtensionsV1beta1ScaleSpec
            //Assert.IsInstanceOfType<ExtensionsV1beta1ScaleSpec> (instance, "variable 'instance' is a ExtensionsV1beta1ScaleSpec");
        }

        /// <summary>
        /// Test the property 'Replicas'
        /// </summary>
        [Test]
        public void ReplicasTest()
        {
            // TODO unit test for the property 'Replicas'
        }

    }

}
