/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing ExtensionsV1beta1DeploymentStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtensionsV1beta1DeploymentStatusTests
    {
        // TODO uncomment below to declare an instance variable for ExtensionsV1beta1DeploymentStatus
        //private ExtensionsV1beta1DeploymentStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtensionsV1beta1DeploymentStatus
            //instance = new ExtensionsV1beta1DeploymentStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtensionsV1beta1DeploymentStatus
        /// </summary>
        [Test]
        public void ExtensionsV1beta1DeploymentStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtensionsV1beta1DeploymentStatus
            //Assert.IsInstanceOfType<ExtensionsV1beta1DeploymentStatus> (instance, "variable 'instance' is a ExtensionsV1beta1DeploymentStatus");
        }

        /// <summary>
        /// Test the property 'AvailableReplicas'
        /// </summary>
        [Test]
        public void AvailableReplicasTest()
        {
            // TODO unit test for the property 'AvailableReplicas'
        }
        /// <summary>
        /// Test the property 'CollisionCount'
        /// </summary>
        [Test]
        public void CollisionCountTest()
        {
            // TODO unit test for the property 'CollisionCount'
        }
        /// <summary>
        /// Test the property 'Conditions'
        /// </summary>
        [Test]
        public void ConditionsTest()
        {
            // TODO unit test for the property 'Conditions'
        }
        /// <summary>
        /// Test the property 'ObservedGeneration'
        /// </summary>
        [Test]
        public void ObservedGenerationTest()
        {
            // TODO unit test for the property 'ObservedGeneration'
        }
        /// <summary>
        /// Test the property 'ReadyReplicas'
        /// </summary>
        [Test]
        public void ReadyReplicasTest()
        {
            // TODO unit test for the property 'ReadyReplicas'
        }
        /// <summary>
        /// Test the property 'Replicas'
        /// </summary>
        [Test]
        public void ReplicasTest()
        {
            // TODO unit test for the property 'Replicas'
        }
        /// <summary>
        /// Test the property 'UnavailableReplicas'
        /// </summary>
        [Test]
        public void UnavailableReplicasTest()
        {
            // TODO unit test for the property 'UnavailableReplicas'
        }
        /// <summary>
        /// Test the property 'UpdatedReplicas'
        /// </summary>
        [Test]
        public void UpdatedReplicasTest()
        {
            // TODO unit test for the property 'UpdatedReplicas'
        }

    }

}
