/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1alpha1RoleRef
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1alpha1RoleRefTests
    {
        // TODO uncomment below to declare an instance variable for V1alpha1RoleRef
        //private V1alpha1RoleRef instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1alpha1RoleRef
            //instance = new V1alpha1RoleRef();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1alpha1RoleRef
        /// </summary>
        [Test]
        public void V1alpha1RoleRefInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1alpha1RoleRef
            //Assert.IsInstanceOfType<V1alpha1RoleRef> (instance, "variable 'instance' is a V1alpha1RoleRef");
        }

        /// <summary>
        /// Test the property 'ApiGroup'
        /// </summary>
        [Test]
        public void ApiGroupTest()
        {
            // TODO unit test for the property 'ApiGroup'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
