/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1APIResourceList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1APIResourceListTests
    {
        // TODO uncomment below to declare an instance variable for V1APIResourceList
        //private V1APIResourceList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1APIResourceList
            //instance = new V1APIResourceList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1APIResourceList
        /// </summary>
        [Test]
        public void V1APIResourceListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1APIResourceList
            //Assert.IsInstanceOfType<V1APIResourceList> (instance, "variable 'instance' is a V1APIResourceList");
        }

        /// <summary>
        /// Test the property 'ApiVersion'
        /// </summary>
        [Test]
        public void ApiVersionTest()
        {
            // TODO unit test for the property 'ApiVersion'
        }
        /// <summary>
        /// Test the property 'GroupVersion'
        /// </summary>
        [Test]
        public void GroupVersionTest()
        {
            // TODO unit test for the property 'GroupVersion'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Test]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }

    }

}
