/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1beta1ClusterRoleBinding
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1beta1ClusterRoleBindingTests
    {
        // TODO uncomment below to declare an instance variable for V1beta1ClusterRoleBinding
        //private V1beta1ClusterRoleBinding instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1beta1ClusterRoleBinding
            //instance = new V1beta1ClusterRoleBinding();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1beta1ClusterRoleBinding
        /// </summary>
        [Test]
        public void V1beta1ClusterRoleBindingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1beta1ClusterRoleBinding
            //Assert.IsInstanceOfType<V1beta1ClusterRoleBinding> (instance, "variable 'instance' is a V1beta1ClusterRoleBinding");
        }

        /// <summary>
        /// Test the property 'ApiVersion'
        /// </summary>
        [Test]
        public void ApiVersionTest()
        {
            // TODO unit test for the property 'ApiVersion'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'RoleRef'
        /// </summary>
        [Test]
        public void RoleRefTest()
        {
            // TODO unit test for the property 'RoleRef'
        }
        /// <summary>
        /// Test the property 'Subjects'
        /// </summary>
        [Test]
        public void SubjectsTest()
        {
            // TODO unit test for the property 'Subjects'
        }

    }

}
