/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1beta1ReplicaSetSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1beta1ReplicaSetSpecTests
    {
        // TODO uncomment below to declare an instance variable for V1beta1ReplicaSetSpec
        //private V1beta1ReplicaSetSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1beta1ReplicaSetSpec
            //instance = new V1beta1ReplicaSetSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1beta1ReplicaSetSpec
        /// </summary>
        [Test]
        public void V1beta1ReplicaSetSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1beta1ReplicaSetSpec
            //Assert.IsInstanceOfType<V1beta1ReplicaSetSpec> (instance, "variable 'instance' is a V1beta1ReplicaSetSpec");
        }

        /// <summary>
        /// Test the property 'MinReadySeconds'
        /// </summary>
        [Test]
        public void MinReadySecondsTest()
        {
            // TODO unit test for the property 'MinReadySeconds'
        }
        /// <summary>
        /// Test the property 'Replicas'
        /// </summary>
        [Test]
        public void ReplicasTest()
        {
            // TODO unit test for the property 'Replicas'
        }
        /// <summary>
        /// Test the property 'Selector'
        /// </summary>
        [Test]
        public void SelectorTest()
        {
            // TODO unit test for the property 'Selector'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

    }

}
