/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1EndpointAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1EndpointAddressTests
    {
        // TODO uncomment below to declare an instance variable for V1EndpointAddress
        //private V1EndpointAddress instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1EndpointAddress
            //instance = new V1EndpointAddress();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1EndpointAddress
        /// </summary>
        [Test]
        public void V1EndpointAddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1EndpointAddress
            //Assert.IsInstanceOfType<V1EndpointAddress> (instance, "variable 'instance' is a V1EndpointAddress");
        }

        /// <summary>
        /// Test the property 'Hostname'
        /// </summary>
        [Test]
        public void HostnameTest()
        {
            // TODO unit test for the property 'Hostname'
        }
        /// <summary>
        /// Test the property 'Ip'
        /// </summary>
        [Test]
        public void IpTest()
        {
            // TODO unit test for the property 'Ip'
        }
        /// <summary>
        /// Test the property 'NodeName'
        /// </summary>
        [Test]
        public void NodeNameTest()
        {
            // TODO unit test for the property 'NodeName'
        }
        /// <summary>
        /// Test the property 'TargetRef'
        /// </summary>
        [Test]
        public void TargetRefTest()
        {
            // TODO unit test for the property 'TargetRef'
        }

    }

}
