/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1ExecAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1ExecActionTests
    {
        // TODO uncomment below to declare an instance variable for V1ExecAction
        //private V1ExecAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1ExecAction
            //instance = new V1ExecAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1ExecAction
        /// </summary>
        [Test]
        public void V1ExecActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1ExecAction
            //Assert.IsInstanceOfType<V1ExecAction> (instance, "variable 'instance' is a V1ExecAction");
        }

        /// <summary>
        /// Test the property 'Command'
        /// </summary>
        [Test]
        public void CommandTest()
        {
            // TODO unit test for the property 'Command'
        }

    }

}
