/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1JobSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1JobSpecTests
    {
        // TODO uncomment below to declare an instance variable for V1JobSpec
        //private V1JobSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1JobSpec
            //instance = new V1JobSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1JobSpec
        /// </summary>
        [Test]
        public void V1JobSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1JobSpec
            //Assert.IsInstanceOfType<V1JobSpec> (instance, "variable 'instance' is a V1JobSpec");
        }

        /// <summary>
        /// Test the property 'ActiveDeadlineSeconds'
        /// </summary>
        [Test]
        public void ActiveDeadlineSecondsTest()
        {
            // TODO unit test for the property 'ActiveDeadlineSeconds'
        }
        /// <summary>
        /// Test the property 'Completions'
        /// </summary>
        [Test]
        public void CompletionsTest()
        {
            // TODO unit test for the property 'Completions'
        }
        /// <summary>
        /// Test the property 'ManualSelector'
        /// </summary>
        [Test]
        public void ManualSelectorTest()
        {
            // TODO unit test for the property 'ManualSelector'
        }
        /// <summary>
        /// Test the property 'Parallelism'
        /// </summary>
        [Test]
        public void ParallelismTest()
        {
            // TODO unit test for the property 'Parallelism'
        }
        /// <summary>
        /// Test the property 'Selector'
        /// </summary>
        [Test]
        public void SelectorTest()
        {
            // TODO unit test for the property 'Selector'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

    }

}
