/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1PortworxVolumeSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1PortworxVolumeSourceTests
    {
        // TODO uncomment below to declare an instance variable for V1PortworxVolumeSource
        //private V1PortworxVolumeSource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1PortworxVolumeSource
            //instance = new V1PortworxVolumeSource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1PortworxVolumeSource
        /// </summary>
        [Test]
        public void V1PortworxVolumeSourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1PortworxVolumeSource
            //Assert.IsInstanceOfType<V1PortworxVolumeSource> (instance, "variable 'instance' is a V1PortworxVolumeSource");
        }

        /// <summary>
        /// Test the property 'FsType'
        /// </summary>
        [Test]
        public void FsTypeTest()
        {
            // TODO unit test for the property 'FsType'
        }
        /// <summary>
        /// Test the property '_ReadOnly'
        /// </summary>
        [Test]
        public void _ReadOnlyTest()
        {
            // TODO unit test for the property '_ReadOnly'
        }
        /// <summary>
        /// Test the property 'VolumeID'
        /// </summary>
        [Test]
        public void VolumeIDTest()
        {
            // TODO unit test for the property 'VolumeID'
        }

    }

}
