/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1RBDVolumeSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1RBDVolumeSourceTests
    {
        // TODO uncomment below to declare an instance variable for V1RBDVolumeSource
        //private V1RBDVolumeSource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1RBDVolumeSource
            //instance = new V1RBDVolumeSource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1RBDVolumeSource
        /// </summary>
        [Test]
        public void V1RBDVolumeSourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1RBDVolumeSource
            //Assert.IsInstanceOfType<V1RBDVolumeSource> (instance, "variable 'instance' is a V1RBDVolumeSource");
        }

        /// <summary>
        /// Test the property 'FsType'
        /// </summary>
        [Test]
        public void FsTypeTest()
        {
            // TODO unit test for the property 'FsType'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'Keyring'
        /// </summary>
        [Test]
        public void KeyringTest()
        {
            // TODO unit test for the property 'Keyring'
        }
        /// <summary>
        /// Test the property 'Monitors'
        /// </summary>
        [Test]
        public void MonitorsTest()
        {
            // TODO unit test for the property 'Monitors'
        }
        /// <summary>
        /// Test the property 'Pool'
        /// </summary>
        [Test]
        public void PoolTest()
        {
            // TODO unit test for the property 'Pool'
        }
        /// <summary>
        /// Test the property '_ReadOnly'
        /// </summary>
        [Test]
        public void _ReadOnlyTest()
        {
            // TODO unit test for the property '_ReadOnly'
        }
        /// <summary>
        /// Test the property 'SecretRef'
        /// </summary>
        [Test]
        public void SecretRefTest()
        {
            // TODO unit test for the property 'SecretRef'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

    }

}
