/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1ReplicationControllerStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1ReplicationControllerStatusTests
    {
        // TODO uncomment below to declare an instance variable for V1ReplicationControllerStatus
        //private V1ReplicationControllerStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1ReplicationControllerStatus
            //instance = new V1ReplicationControllerStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1ReplicationControllerStatus
        /// </summary>
        [Test]
        public void V1ReplicationControllerStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1ReplicationControllerStatus
            //Assert.IsInstanceOfType<V1ReplicationControllerStatus> (instance, "variable 'instance' is a V1ReplicationControllerStatus");
        }

        /// <summary>
        /// Test the property 'AvailableReplicas'
        /// </summary>
        [Test]
        public void AvailableReplicasTest()
        {
            // TODO unit test for the property 'AvailableReplicas'
        }
        /// <summary>
        /// Test the property 'Conditions'
        /// </summary>
        [Test]
        public void ConditionsTest()
        {
            // TODO unit test for the property 'Conditions'
        }
        /// <summary>
        /// Test the property 'FullyLabeledReplicas'
        /// </summary>
        [Test]
        public void FullyLabeledReplicasTest()
        {
            // TODO unit test for the property 'FullyLabeledReplicas'
        }
        /// <summary>
        /// Test the property 'ObservedGeneration'
        /// </summary>
        [Test]
        public void ObservedGenerationTest()
        {
            // TODO unit test for the property 'ObservedGeneration'
        }
        /// <summary>
        /// Test the property 'ReadyReplicas'
        /// </summary>
        [Test]
        public void ReadyReplicasTest()
        {
            // TODO unit test for the property 'ReadyReplicas'
        }
        /// <summary>
        /// Test the property 'Replicas'
        /// </summary>
        [Test]
        public void ReplicasTest()
        {
            // TODO unit test for the property 'Replicas'
        }

    }

}
