/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1StatusDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1StatusDetailsTests
    {
        // TODO uncomment below to declare an instance variable for V1StatusDetails
        //private V1StatusDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1StatusDetails
            //instance = new V1StatusDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1StatusDetails
        /// </summary>
        [Test]
        public void V1StatusDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1StatusDetails
            //Assert.IsInstanceOfType<V1StatusDetails> (instance, "variable 'instance' is a V1StatusDetails");
        }

        /// <summary>
        /// Test the property 'Causes'
        /// </summary>
        [Test]
        public void CausesTest()
        {
            // TODO unit test for the property 'Causes'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RetryAfterSeconds'
        /// </summary>
        [Test]
        public void RetryAfterSecondsTest()
        {
            // TODO unit test for the property 'RetryAfterSeconds'
        }
        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Test]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }

    }

}
