/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Kubernetes.DotNet.Client.SwaggerDateConverter;

namespace Kubernetes.DotNet.Model
{
    /// <summary>
    /// AzureDisk represents an Azure Data Disk mount on the host and bind mount to the pod.
    /// </summary>
    [DataContract]
    public partial class V1AzureDiskVolumeSource :  IEquatable<V1AzureDiskVolumeSource>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1AzureDiskVolumeSource" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V1AzureDiskVolumeSource() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1AzureDiskVolumeSource" /> class.
        /// </summary>
        /// <param name="CachingMode">Host Caching mode: None, Read Only, Read Write..</param>
        /// <param name="DiskName">The Name of the data disk in the blob storage (required).</param>
        /// <param name="DiskURI">The URI the data disk in the blob storage (required).</param>
        /// <param name="FsType">Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \&quot;ext4\&quot;, \&quot;xfs\&quot;, \&quot;ntfs\&quot;. Implicitly inferred to be \&quot;ext4\&quot; if unspecified..</param>
        /// <param name="Kind">Expected values Shared: mulitple blob disks per storage account  Dedicated: single blob disk per storage account  Managed: azure managed data disk (only in managed availability set). defaults to shared.</param>
        /// <param name="_ReadOnly">Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts..</param>
        public V1AzureDiskVolumeSource(string CachingMode = default(string), string DiskName = default(string), string DiskURI = default(string), string FsType = default(string), string Kind = default(string), bool? _ReadOnly = default(bool?))
        {
            // to ensure "DiskName" is required (not null)
            if (DiskName == null)
            {
                throw new InvalidDataException("DiskName is a required property for V1AzureDiskVolumeSource and cannot be null");
            }
            else
            {
                this.DiskName = DiskName;
            }
            // to ensure "DiskURI" is required (not null)
            if (DiskURI == null)
            {
                throw new InvalidDataException("DiskURI is a required property for V1AzureDiskVolumeSource and cannot be null");
            }
            else
            {
                this.DiskURI = DiskURI;
            }
            this.CachingMode = CachingMode;
            this.FsType = FsType;
            this.Kind = Kind;
            this._ReadOnly = _ReadOnly;
        }
        
        /// <summary>
        /// Host Caching mode: None, Read Only, Read Write.
        /// </summary>
        /// <value>Host Caching mode: None, Read Only, Read Write.</value>
        [DataMember(Name="cachingMode", EmitDefaultValue=false)]
        public string CachingMode { get; set; }

        /// <summary>
        /// The Name of the data disk in the blob storage
        /// </summary>
        /// <value>The Name of the data disk in the blob storage</value>
        [DataMember(Name="diskName", EmitDefaultValue=false)]
        public string DiskName { get; set; }

        /// <summary>
        /// The URI the data disk in the blob storage
        /// </summary>
        /// <value>The URI the data disk in the blob storage</value>
        [DataMember(Name="diskURI", EmitDefaultValue=false)]
        public string DiskURI { get; set; }

        /// <summary>
        /// Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \&quot;ext4\&quot;, \&quot;xfs\&quot;, \&quot;ntfs\&quot;. Implicitly inferred to be \&quot;ext4\&quot; if unspecified.
        /// </summary>
        /// <value>Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \&quot;ext4\&quot;, \&quot;xfs\&quot;, \&quot;ntfs\&quot;. Implicitly inferred to be \&quot;ext4\&quot; if unspecified.</value>
        [DataMember(Name="fsType", EmitDefaultValue=false)]
        public string FsType { get; set; }

        /// <summary>
        /// Expected values Shared: mulitple blob disks per storage account  Dedicated: single blob disk per storage account  Managed: azure managed data disk (only in managed availability set). defaults to shared
        /// </summary>
        /// <value>Expected values Shared: mulitple blob disks per storage account  Dedicated: single blob disk per storage account  Managed: azure managed data disk (only in managed availability set). defaults to shared</value>
        [DataMember(Name="kind", EmitDefaultValue=false)]
        public string Kind { get; set; }

        /// <summary>
        /// Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
        /// </summary>
        /// <value>Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.</value>
        [DataMember(Name="readOnly", EmitDefaultValue=false)]
        public bool? _ReadOnly { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class V1AzureDiskVolumeSource {\n");
            sb.Append("  CachingMode: ").Append(CachingMode).Append("\n");
            sb.Append("  DiskName: ").Append(DiskName).Append("\n");
            sb.Append("  DiskURI: ").Append(DiskURI).Append("\n");
            sb.Append("  FsType: ").Append(FsType).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  _ReadOnly: ").Append(_ReadOnly).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as V1AzureDiskVolumeSource);
        }

        /// <summary>
        /// Returns true if V1AzureDiskVolumeSource instances are equal
        /// </summary>
        /// <param name="other">Instance of V1AzureDiskVolumeSource to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V1AzureDiskVolumeSource other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CachingMode == other.CachingMode ||
                    this.CachingMode != null &&
                    this.CachingMode.Equals(other.CachingMode)
                ) && 
                (
                    this.DiskName == other.DiskName ||
                    this.DiskName != null &&
                    this.DiskName.Equals(other.DiskName)
                ) && 
                (
                    this.DiskURI == other.DiskURI ||
                    this.DiskURI != null &&
                    this.DiskURI.Equals(other.DiskURI)
                ) && 
                (
                    this.FsType == other.FsType ||
                    this.FsType != null &&
                    this.FsType.Equals(other.FsType)
                ) && 
                (
                    this.Kind == other.Kind ||
                    this.Kind != null &&
                    this.Kind.Equals(other.Kind)
                ) && 
                (
                    this._ReadOnly == other._ReadOnly ||
                    this._ReadOnly != null &&
                    this._ReadOnly.Equals(other._ReadOnly)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CachingMode != null)
                    hash = hash * 59 + this.CachingMode.GetHashCode();
                if (this.DiskName != null)
                    hash = hash * 59 + this.DiskName.GetHashCode();
                if (this.DiskURI != null)
                    hash = hash * 59 + this.DiskURI.GetHashCode();
                if (this.FsType != null)
                    hash = hash * 59 + this.FsType.GetHashCode();
                if (this.Kind != null)
                    hash = hash * 59 + this.Kind.GetHashCode();
                if (this._ReadOnly != null)
                    hash = hash * 59 + this._ReadOnly.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
