/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Kubernetes.DotNet.Client.SwaggerDateConverter;

namespace Kubernetes.DotNet.Model
{
    /// <summary>
    /// current status of a horizontal pod autoscaler
    /// </summary>
    [DataContract]
    public partial class V1HorizontalPodAutoscalerStatus :  IEquatable<V1HorizontalPodAutoscalerStatus>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1HorizontalPodAutoscalerStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V1HorizontalPodAutoscalerStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1HorizontalPodAutoscalerStatus" /> class.
        /// </summary>
        /// <param name="CurrentCPUUtilizationPercentage">current average CPU utilization over all pods, represented as a percentage of requested CPU, e.g. 70 means that an average pod is using now 70% of its requested CPU..</param>
        /// <param name="CurrentReplicas">current number of replicas of pods managed by this autoscaler. (required).</param>
        /// <param name="DesiredReplicas">desired number of replicas of pods managed by this autoscaler. (required).</param>
        /// <param name="LastScaleTime">last time the HorizontalPodAutoscaler scaled the number of pods; used by the autoscaler to control how often the number of pods is changed..</param>
        /// <param name="ObservedGeneration">most recent generation observed by this autoscaler..</param>
        public V1HorizontalPodAutoscalerStatus(int? CurrentCPUUtilizationPercentage = default(int?), int? CurrentReplicas = default(int?), int? DesiredReplicas = default(int?), DateTime? LastScaleTime = default(DateTime?), long? ObservedGeneration = default(long?))
        {
            // to ensure "CurrentReplicas" is required (not null)
            if (CurrentReplicas == null)
            {
                throw new InvalidDataException("CurrentReplicas is a required property for V1HorizontalPodAutoscalerStatus and cannot be null");
            }
            else
            {
                this.CurrentReplicas = CurrentReplicas;
            }
            // to ensure "DesiredReplicas" is required (not null)
            if (DesiredReplicas == null)
            {
                throw new InvalidDataException("DesiredReplicas is a required property for V1HorizontalPodAutoscalerStatus and cannot be null");
            }
            else
            {
                this.DesiredReplicas = DesiredReplicas;
            }
            this.CurrentCPUUtilizationPercentage = CurrentCPUUtilizationPercentage;
            this.LastScaleTime = LastScaleTime;
            this.ObservedGeneration = ObservedGeneration;
        }
        
        /// <summary>
        /// current average CPU utilization over all pods, represented as a percentage of requested CPU, e.g. 70 means that an average pod is using now 70% of its requested CPU.
        /// </summary>
        /// <value>current average CPU utilization over all pods, represented as a percentage of requested CPU, e.g. 70 means that an average pod is using now 70% of its requested CPU.</value>
        [DataMember(Name="currentCPUUtilizationPercentage", EmitDefaultValue=false)]
        public int? CurrentCPUUtilizationPercentage { get; set; }

        /// <summary>
        /// current number of replicas of pods managed by this autoscaler.
        /// </summary>
        /// <value>current number of replicas of pods managed by this autoscaler.</value>
        [DataMember(Name="currentReplicas", EmitDefaultValue=false)]
        public int? CurrentReplicas { get; set; }

        /// <summary>
        /// desired number of replicas of pods managed by this autoscaler.
        /// </summary>
        /// <value>desired number of replicas of pods managed by this autoscaler.</value>
        [DataMember(Name="desiredReplicas", EmitDefaultValue=false)]
        public int? DesiredReplicas { get; set; }

        /// <summary>
        /// last time the HorizontalPodAutoscaler scaled the number of pods; used by the autoscaler to control how often the number of pods is changed.
        /// </summary>
        /// <value>last time the HorizontalPodAutoscaler scaled the number of pods; used by the autoscaler to control how often the number of pods is changed.</value>
        [DataMember(Name="lastScaleTime", EmitDefaultValue=false)]
        public DateTime? LastScaleTime { get; set; }

        /// <summary>
        /// most recent generation observed by this autoscaler.
        /// </summary>
        /// <value>most recent generation observed by this autoscaler.</value>
        [DataMember(Name="observedGeneration", EmitDefaultValue=false)]
        public long? ObservedGeneration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class V1HorizontalPodAutoscalerStatus {\n");
            sb.Append("  CurrentCPUUtilizationPercentage: ").Append(CurrentCPUUtilizationPercentage).Append("\n");
            sb.Append("  CurrentReplicas: ").Append(CurrentReplicas).Append("\n");
            sb.Append("  DesiredReplicas: ").Append(DesiredReplicas).Append("\n");
            sb.Append("  LastScaleTime: ").Append(LastScaleTime).Append("\n");
            sb.Append("  ObservedGeneration: ").Append(ObservedGeneration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as V1HorizontalPodAutoscalerStatus);
        }

        /// <summary>
        /// Returns true if V1HorizontalPodAutoscalerStatus instances are equal
        /// </summary>
        /// <param name="other">Instance of V1HorizontalPodAutoscalerStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V1HorizontalPodAutoscalerStatus other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CurrentCPUUtilizationPercentage == other.CurrentCPUUtilizationPercentage ||
                    this.CurrentCPUUtilizationPercentage != null &&
                    this.CurrentCPUUtilizationPercentage.Equals(other.CurrentCPUUtilizationPercentage)
                ) && 
                (
                    this.CurrentReplicas == other.CurrentReplicas ||
                    this.CurrentReplicas != null &&
                    this.CurrentReplicas.Equals(other.CurrentReplicas)
                ) && 
                (
                    this.DesiredReplicas == other.DesiredReplicas ||
                    this.DesiredReplicas != null &&
                    this.DesiredReplicas.Equals(other.DesiredReplicas)
                ) && 
                (
                    this.LastScaleTime == other.LastScaleTime ||
                    this.LastScaleTime != null &&
                    this.LastScaleTime.Equals(other.LastScaleTime)
                ) && 
                (
                    this.ObservedGeneration == other.ObservedGeneration ||
                    this.ObservedGeneration != null &&
                    this.ObservedGeneration.Equals(other.ObservedGeneration)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CurrentCPUUtilizationPercentage != null)
                    hash = hash * 59 + this.CurrentCPUUtilizationPercentage.GetHashCode();
                if (this.CurrentReplicas != null)
                    hash = hash * 59 + this.CurrentReplicas.GetHashCode();
                if (this.DesiredReplicas != null)
                    hash = hash * 59 + this.DesiredReplicas.GetHashCode();
                if (this.LastScaleTime != null)
                    hash = hash * 59 + this.LastScaleTime.GetHashCode();
                if (this.ObservedGeneration != null)
                    hash = hash * 59 + this.ObservedGeneration.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
