/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Kubernetes.DotNet.Client.SwaggerDateConverter;

namespace Kubernetes.DotNet.Model
{
    /// <summary>
    /// OwnerReference contains enough information to let you identify an owning object. Currently, an owning object must be in the same namespace, so there is no namespace field.
    /// </summary>
    [DataContract]
    public partial class V1OwnerReference :  IEquatable<V1OwnerReference>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1OwnerReference" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V1OwnerReference() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1OwnerReference" /> class.
        /// </summary>
        /// <param name="ApiVersion">API version of the referent. (required).</param>
        /// <param name="BlockOwnerDeletion">If true, AND if the owner has the \&quot;foregroundDeletion\&quot; finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. Defaults to false. To set this field, a user needs \&quot;delete\&quot; permission of the owner, otherwise 422 (Unprocessable Entity) will be returned..</param>
        /// <param name="Controller">If true, this reference points to the managing controller..</param>
        /// <param name="Kind">Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds (required).</param>
        /// <param name="Name">Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names (required).</param>
        /// <param name="Uid">UID of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#uids (required).</param>
        public V1OwnerReference(string ApiVersion = default(string), bool? BlockOwnerDeletion = default(bool?), bool? Controller = default(bool?), string Kind = default(string), string Name = default(string), string Uid = default(string))
        {
            // to ensure "ApiVersion" is required (not null)
            if (ApiVersion == null)
            {
                throw new InvalidDataException("ApiVersion is a required property for V1OwnerReference and cannot be null");
            }
            else
            {
                this.ApiVersion = ApiVersion;
            }
            // to ensure "Kind" is required (not null)
            if (Kind == null)
            {
                throw new InvalidDataException("Kind is a required property for V1OwnerReference and cannot be null");
            }
            else
            {
                this.Kind = Kind;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for V1OwnerReference and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // to ensure "Uid" is required (not null)
            if (Uid == null)
            {
                throw new InvalidDataException("Uid is a required property for V1OwnerReference and cannot be null");
            }
            else
            {
                this.Uid = Uid;
            }
            this.BlockOwnerDeletion = BlockOwnerDeletion;
            this.Controller = Controller;
        }
        
        /// <summary>
        /// API version of the referent.
        /// </summary>
        /// <value>API version of the referent.</value>
        [DataMember(Name="apiVersion", EmitDefaultValue=false)]
        public string ApiVersion { get; set; }

        /// <summary>
        /// If true, AND if the owner has the \&quot;foregroundDeletion\&quot; finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. Defaults to false. To set this field, a user needs \&quot;delete\&quot; permission of the owner, otherwise 422 (Unprocessable Entity) will be returned.
        /// </summary>
        /// <value>If true, AND if the owner has the \&quot;foregroundDeletion\&quot; finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. Defaults to false. To set this field, a user needs \&quot;delete\&quot; permission of the owner, otherwise 422 (Unprocessable Entity) will be returned.</value>
        [DataMember(Name="blockOwnerDeletion", EmitDefaultValue=false)]
        public bool? BlockOwnerDeletion { get; set; }

        /// <summary>
        /// If true, this reference points to the managing controller.
        /// </summary>
        /// <value>If true, this reference points to the managing controller.</value>
        [DataMember(Name="controller", EmitDefaultValue=false)]
        public bool? Controller { get; set; }

        /// <summary>
        /// Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
        /// </summary>
        /// <value>Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds</value>
        [DataMember(Name="kind", EmitDefaultValue=false)]
        public string Kind { get; set; }

        /// <summary>
        /// Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names
        /// </summary>
        /// <value>Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// UID of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#uids
        /// </summary>
        /// <value>UID of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#uids</value>
        [DataMember(Name="uid", EmitDefaultValue=false)]
        public string Uid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class V1OwnerReference {\n");
            sb.Append("  ApiVersion: ").Append(ApiVersion).Append("\n");
            sb.Append("  BlockOwnerDeletion: ").Append(BlockOwnerDeletion).Append("\n");
            sb.Append("  Controller: ").Append(Controller).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Uid: ").Append(Uid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as V1OwnerReference);
        }

        /// <summary>
        /// Returns true if V1OwnerReference instances are equal
        /// </summary>
        /// <param name="other">Instance of V1OwnerReference to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V1OwnerReference other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ApiVersion == other.ApiVersion ||
                    this.ApiVersion != null &&
                    this.ApiVersion.Equals(other.ApiVersion)
                ) && 
                (
                    this.BlockOwnerDeletion == other.BlockOwnerDeletion ||
                    this.BlockOwnerDeletion != null &&
                    this.BlockOwnerDeletion.Equals(other.BlockOwnerDeletion)
                ) && 
                (
                    this.Controller == other.Controller ||
                    this.Controller != null &&
                    this.Controller.Equals(other.Controller)
                ) && 
                (
                    this.Kind == other.Kind ||
                    this.Kind != null &&
                    this.Kind.Equals(other.Kind)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Uid == other.Uid ||
                    this.Uid != null &&
                    this.Uid.Equals(other.Uid)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ApiVersion != null)
                    hash = hash * 59 + this.ApiVersion.GetHashCode();
                if (this.BlockOwnerDeletion != null)
                    hash = hash * 59 + this.BlockOwnerDeletion.GetHashCode();
                if (this.Controller != null)
                    hash = hash * 59 + this.Controller.GetHashCode();
                if (this.Kind != null)
                    hash = hash * 59 + this.Kind.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.Uid != null)
                    hash = hash * 59 + this.Uid.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
