/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Kubernetes.DotNet.Client;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing Apiregistration_v1beta1Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class Apiregistration_v1beta1ApiTests
    {
        private Apiregistration_v1beta1Api instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Apiregistration_v1beta1Api();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Apiregistration_v1beta1Api
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' Apiregistration_v1beta1Api
            //Assert.IsInstanceOfType(typeof(Apiregistration_v1beta1Api), instance, "instance is a Apiregistration_v1beta1Api");
        }

        
        /// <summary>
        /// Test CreateAPIService
        /// </summary>
        [Test]
        public void CreateAPIServiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //V1beta1APIService body = null;
            //string pretty = null;
            //var response = instance.CreateAPIService(body, pretty);
            //Assert.IsInstanceOf<V1beta1APIService> (response, "response is V1beta1APIService");
        }
        
        /// <summary>
        /// Test DeleteAPIService
        /// </summary>
        [Test]
        public void DeleteAPIServiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //V1DeleteOptions body = null;
            //string pretty = null;
            //int? gracePeriodSeconds = null;
            //bool? orphanDependents = null;
            //string propagationPolicy = null;
            //var response = instance.DeleteAPIService(name, body, pretty, gracePeriodSeconds, orphanDependents, propagationPolicy);
            //Assert.IsInstanceOf<V1Status> (response, "response is V1Status");
        }
        
        /// <summary>
        /// Test DeleteCollectionAPIService
        /// </summary>
        [Test]
        public void DeleteCollectionAPIServiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string pretty = null;
            //string fieldSelector = null;
            //bool? includeUninitialized = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.DeleteCollectionAPIService(pretty, fieldSelector, includeUninitialized, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V1Status> (response, "response is V1Status");
        }
        
        /// <summary>
        /// Test GetAPIResources
        /// </summary>
        [Test]
        public void GetAPIResourcesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAPIResources();
            //Assert.IsInstanceOf<V1APIResourceList> (response, "response is V1APIResourceList");
        }
        
        /// <summary>
        /// Test ListAPIService
        /// </summary>
        [Test]
        public void ListAPIServiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string pretty = null;
            //string fieldSelector = null;
            //bool? includeUninitialized = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.ListAPIService(pretty, fieldSelector, includeUninitialized, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V1beta1APIServiceList> (response, "response is V1beta1APIServiceList");
        }
        
        /// <summary>
        /// Test PatchAPIService
        /// </summary>
        [Test]
        public void PatchAPIServiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //Object body = null;
            //string pretty = null;
            //var response = instance.PatchAPIService(name, body, pretty);
            //Assert.IsInstanceOf<V1beta1APIService> (response, "response is V1beta1APIService");
        }
        
        /// <summary>
        /// Test ReadAPIService
        /// </summary>
        [Test]
        public void ReadAPIServiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string pretty = null;
            //bool? exact = null;
            //bool? export = null;
            //var response = instance.ReadAPIService(name, pretty, exact, export);
            //Assert.IsInstanceOf<V1beta1APIService> (response, "response is V1beta1APIService");
        }
        
        /// <summary>
        /// Test ReplaceAPIService
        /// </summary>
        [Test]
        public void ReplaceAPIServiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //V1beta1APIService body = null;
            //string pretty = null;
            //var response = instance.ReplaceAPIService(name, body, pretty);
            //Assert.IsInstanceOf<V1beta1APIService> (response, "response is V1beta1APIService");
        }
        
        /// <summary>
        /// Test ReplaceAPIServiceStatus
        /// </summary>
        [Test]
        public void ReplaceAPIServiceStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //V1beta1APIService body = null;
            //string pretty = null;
            //var response = instance.ReplaceAPIServiceStatus(name, body, pretty);
            //Assert.IsInstanceOf<V1beta1APIService> (response, "response is V1beta1APIService");
        }
        
    }

}
