/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Kubernetes.DotNet.Client;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing Batch_v1Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class Batch_v1ApiTests
    {
        private Batch_v1Api instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Batch_v1Api();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Batch_v1Api
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' Batch_v1Api
            //Assert.IsInstanceOfType(typeof(Batch_v1Api), instance, "instance is a Batch_v1Api");
        }

        
        /// <summary>
        /// Test CreateNamespacedJob
        /// </summary>
        [Test]
        public void CreateNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //V1Job body = null;
            //string pretty = null;
            //var response = instance.CreateNamespacedJob(_namespace, body, pretty);
            //Assert.IsInstanceOf<V1Job> (response, "response is V1Job");
        }
        
        /// <summary>
        /// Test DeleteCollectionNamespacedJob
        /// </summary>
        [Test]
        public void DeleteCollectionNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //string pretty = null;
            //string fieldSelector = null;
            //bool? includeUninitialized = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.DeleteCollectionNamespacedJob(_namespace, pretty, fieldSelector, includeUninitialized, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V1Status> (response, "response is V1Status");
        }
        
        /// <summary>
        /// Test DeleteNamespacedJob
        /// </summary>
        [Test]
        public void DeleteNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V1DeleteOptions body = null;
            //string pretty = null;
            //int? gracePeriodSeconds = null;
            //bool? orphanDependents = null;
            //string propagationPolicy = null;
            //var response = instance.DeleteNamespacedJob(name, _namespace, body, pretty, gracePeriodSeconds, orphanDependents, propagationPolicy);
            //Assert.IsInstanceOf<V1Status> (response, "response is V1Status");
        }
        
        /// <summary>
        /// Test GetAPIResources
        /// </summary>
        [Test]
        public void GetAPIResourcesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAPIResources();
            //Assert.IsInstanceOf<V1APIResourceList> (response, "response is V1APIResourceList");
        }
        
        /// <summary>
        /// Test ListJobForAllNamespaces
        /// </summary>
        [Test]
        public void ListJobForAllNamespacesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fieldSelector = null;
            //bool? includeUninitialized = null;
            //string labelSelector = null;
            //string pretty = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.ListJobForAllNamespaces(fieldSelector, includeUninitialized, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V1JobList> (response, "response is V1JobList");
        }
        
        /// <summary>
        /// Test ListNamespacedJob
        /// </summary>
        [Test]
        public void ListNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //string pretty = null;
            //string fieldSelector = null;
            //bool? includeUninitialized = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.ListNamespacedJob(_namespace, pretty, fieldSelector, includeUninitialized, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V1JobList> (response, "response is V1JobList");
        }
        
        /// <summary>
        /// Test PatchNamespacedJob
        /// </summary>
        [Test]
        public void PatchNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //Object body = null;
            //string pretty = null;
            //var response = instance.PatchNamespacedJob(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V1Job> (response, "response is V1Job");
        }
        
        /// <summary>
        /// Test PatchNamespacedJobStatus
        /// </summary>
        [Test]
        public void PatchNamespacedJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //Object body = null;
            //string pretty = null;
            //var response = instance.PatchNamespacedJobStatus(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V1Job> (response, "response is V1Job");
        }
        
        /// <summary>
        /// Test ReadNamespacedJob
        /// </summary>
        [Test]
        public void ReadNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //string pretty = null;
            //bool? exact = null;
            //bool? export = null;
            //var response = instance.ReadNamespacedJob(name, _namespace, pretty, exact, export);
            //Assert.IsInstanceOf<V1Job> (response, "response is V1Job");
        }
        
        /// <summary>
        /// Test ReadNamespacedJobStatus
        /// </summary>
        [Test]
        public void ReadNamespacedJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //string pretty = null;
            //var response = instance.ReadNamespacedJobStatus(name, _namespace, pretty);
            //Assert.IsInstanceOf<V1Job> (response, "response is V1Job");
        }
        
        /// <summary>
        /// Test ReplaceNamespacedJob
        /// </summary>
        [Test]
        public void ReplaceNamespacedJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V1Job body = null;
            //string pretty = null;
            //var response = instance.ReplaceNamespacedJob(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V1Job> (response, "response is V1Job");
        }
        
        /// <summary>
        /// Test ReplaceNamespacedJobStatus
        /// </summary>
        [Test]
        public void ReplaceNamespacedJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V1Job body = null;
            //string pretty = null;
            //var response = instance.ReplaceNamespacedJobStatus(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V1Job> (response, "response is V1Job");
        }
        
    }

}
