/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Kubernetes.DotNet.Client;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing Settings_v1alpha1Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class Settings_v1alpha1ApiTests
    {
        private Settings_v1alpha1Api instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Settings_v1alpha1Api();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Settings_v1alpha1Api
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' Settings_v1alpha1Api
            //Assert.IsInstanceOfType(typeof(Settings_v1alpha1Api), instance, "instance is a Settings_v1alpha1Api");
        }

        
        /// <summary>
        /// Test CreateNamespacedPodPreset
        /// </summary>
        [Test]
        public void CreateNamespacedPodPresetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //V1alpha1PodPreset body = null;
            //string pretty = null;
            //var response = instance.CreateNamespacedPodPreset(_namespace, body, pretty);
            //Assert.IsInstanceOf<V1alpha1PodPreset> (response, "response is V1alpha1PodPreset");
        }
        
        /// <summary>
        /// Test DeleteCollectionNamespacedPodPreset
        /// </summary>
        [Test]
        public void DeleteCollectionNamespacedPodPresetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //string pretty = null;
            //string fieldSelector = null;
            //bool? includeUninitialized = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.DeleteCollectionNamespacedPodPreset(_namespace, pretty, fieldSelector, includeUninitialized, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V1Status> (response, "response is V1Status");
        }
        
        /// <summary>
        /// Test DeleteNamespacedPodPreset
        /// </summary>
        [Test]
        public void DeleteNamespacedPodPresetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V1DeleteOptions body = null;
            //string pretty = null;
            //int? gracePeriodSeconds = null;
            //bool? orphanDependents = null;
            //string propagationPolicy = null;
            //var response = instance.DeleteNamespacedPodPreset(name, _namespace, body, pretty, gracePeriodSeconds, orphanDependents, propagationPolicy);
            //Assert.IsInstanceOf<V1Status> (response, "response is V1Status");
        }
        
        /// <summary>
        /// Test GetAPIResources
        /// </summary>
        [Test]
        public void GetAPIResourcesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAPIResources();
            //Assert.IsInstanceOf<V1APIResourceList> (response, "response is V1APIResourceList");
        }
        
        /// <summary>
        /// Test ListNamespacedPodPreset
        /// </summary>
        [Test]
        public void ListNamespacedPodPresetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //string pretty = null;
            //string fieldSelector = null;
            //bool? includeUninitialized = null;
            //string labelSelector = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.ListNamespacedPodPreset(_namespace, pretty, fieldSelector, includeUninitialized, labelSelector, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V1alpha1PodPresetList> (response, "response is V1alpha1PodPresetList");
        }
        
        /// <summary>
        /// Test ListPodPresetForAllNamespaces
        /// </summary>
        [Test]
        public void ListPodPresetForAllNamespacesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fieldSelector = null;
            //bool? includeUninitialized = null;
            //string labelSelector = null;
            //string pretty = null;
            //string resourceVersion = null;
            //int? timeoutSeconds = null;
            //bool? watch = null;
            //var response = instance.ListPodPresetForAllNamespaces(fieldSelector, includeUninitialized, labelSelector, pretty, resourceVersion, timeoutSeconds, watch);
            //Assert.IsInstanceOf<V1alpha1PodPresetList> (response, "response is V1alpha1PodPresetList");
        }
        
        /// <summary>
        /// Test PatchNamespacedPodPreset
        /// </summary>
        [Test]
        public void PatchNamespacedPodPresetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //Object body = null;
            //string pretty = null;
            //var response = instance.PatchNamespacedPodPreset(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V1alpha1PodPreset> (response, "response is V1alpha1PodPreset");
        }
        
        /// <summary>
        /// Test ReadNamespacedPodPreset
        /// </summary>
        [Test]
        public void ReadNamespacedPodPresetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //string pretty = null;
            //bool? exact = null;
            //bool? export = null;
            //var response = instance.ReadNamespacedPodPreset(name, _namespace, pretty, exact, export);
            //Assert.IsInstanceOf<V1alpha1PodPreset> (response, "response is V1alpha1PodPreset");
        }
        
        /// <summary>
        /// Test ReplaceNamespacedPodPreset
        /// </summary>
        [Test]
        public void ReplaceNamespacedPodPresetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string _namespace = null;
            //V1alpha1PodPreset body = null;
            //string pretty = null;
            //var response = instance.ReplaceNamespacedPodPreset(name, _namespace, body, pretty);
            //Assert.IsInstanceOf<V1alpha1PodPreset> (response, "response is V1alpha1PodPreset");
        }
        
    }

}
