/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing ExtensionsV1beta1DeploymentSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtensionsV1beta1DeploymentSpecTests
    {
        // TODO uncomment below to declare an instance variable for ExtensionsV1beta1DeploymentSpec
        //private ExtensionsV1beta1DeploymentSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtensionsV1beta1DeploymentSpec
            //instance = new ExtensionsV1beta1DeploymentSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtensionsV1beta1DeploymentSpec
        /// </summary>
        [Test]
        public void ExtensionsV1beta1DeploymentSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtensionsV1beta1DeploymentSpec
            //Assert.IsInstanceOfType<ExtensionsV1beta1DeploymentSpec> (instance, "variable 'instance' is a ExtensionsV1beta1DeploymentSpec");
        }

        /// <summary>
        /// Test the property 'MinReadySeconds'
        /// </summary>
        [Test]
        public void MinReadySecondsTest()
        {
            // TODO unit test for the property 'MinReadySeconds'
        }
        /// <summary>
        /// Test the property 'Paused'
        /// </summary>
        [Test]
        public void PausedTest()
        {
            // TODO unit test for the property 'Paused'
        }
        /// <summary>
        /// Test the property 'ProgressDeadlineSeconds'
        /// </summary>
        [Test]
        public void ProgressDeadlineSecondsTest()
        {
            // TODO unit test for the property 'ProgressDeadlineSeconds'
        }
        /// <summary>
        /// Test the property 'Replicas'
        /// </summary>
        [Test]
        public void ReplicasTest()
        {
            // TODO unit test for the property 'Replicas'
        }
        /// <summary>
        /// Test the property 'RevisionHistoryLimit'
        /// </summary>
        [Test]
        public void RevisionHistoryLimitTest()
        {
            // TODO unit test for the property 'RevisionHistoryLimit'
        }
        /// <summary>
        /// Test the property 'RollbackTo'
        /// </summary>
        [Test]
        public void RollbackToTest()
        {
            // TODO unit test for the property 'RollbackTo'
        }
        /// <summary>
        /// Test the property 'Selector'
        /// </summary>
        [Test]
        public void SelectorTest()
        {
            // TODO unit test for the property 'Selector'
        }
        /// <summary>
        /// Test the property 'Strategy'
        /// </summary>
        [Test]
        public void StrategyTest()
        {
            // TODO unit test for the property 'Strategy'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Test]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

    }

}
