/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1beta1CertificateSigningRequestSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1beta1CertificateSigningRequestSpecTests
    {
        // TODO uncomment below to declare an instance variable for V1beta1CertificateSigningRequestSpec
        //private V1beta1CertificateSigningRequestSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1beta1CertificateSigningRequestSpec
            //instance = new V1beta1CertificateSigningRequestSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1beta1CertificateSigningRequestSpec
        /// </summary>
        [Test]
        public void V1beta1CertificateSigningRequestSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1beta1CertificateSigningRequestSpec
            //Assert.IsInstanceOfType<V1beta1CertificateSigningRequestSpec> (instance, "variable 'instance' is a V1beta1CertificateSigningRequestSpec");
        }

        /// <summary>
        /// Test the property 'Extra'
        /// </summary>
        [Test]
        public void ExtraTest()
        {
            // TODO unit test for the property 'Extra'
        }
        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Test]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }
        /// <summary>
        /// Test the property 'Request'
        /// </summary>
        [Test]
        public void RequestTest()
        {
            // TODO unit test for the property 'Request'
        }
        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Test]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }
        /// <summary>
        /// Test the property 'Usages'
        /// </summary>
        [Test]
        public void UsagesTest()
        {
            // TODO unit test for the property 'Usages'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
