/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1beta1Subject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1beta1SubjectTests
    {
        // TODO uncomment below to declare an instance variable for V1beta1Subject
        //private V1beta1Subject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1beta1Subject
            //instance = new V1beta1Subject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1beta1Subject
        /// </summary>
        [Test]
        public void V1beta1SubjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1beta1Subject
            //Assert.IsInstanceOfType<V1beta1Subject> (instance, "variable 'instance' is a V1beta1Subject");
        }

        /// <summary>
        /// Test the property 'ApiGroup'
        /// </summary>
        [Test]
        public void ApiGroupTest()
        {
            // TODO unit test for the property 'ApiGroup'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Test]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property '_Namespace'
        /// </summary>
        [Test]
        public void _NamespaceTest()
        {
            // TODO unit test for the property '_Namespace'
        }

    }

}
