/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1ContainerState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1ContainerStateTests
    {
        // TODO uncomment below to declare an instance variable for V1ContainerState
        //private V1ContainerState instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1ContainerState
            //instance = new V1ContainerState();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1ContainerState
        /// </summary>
        [Test]
        public void V1ContainerStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1ContainerState
            //Assert.IsInstanceOfType<V1ContainerState> (instance, "variable 'instance' is a V1ContainerState");
        }

        /// <summary>
        /// Test the property 'Running'
        /// </summary>
        [Test]
        public void RunningTest()
        {
            // TODO unit test for the property 'Running'
        }
        /// <summary>
        /// Test the property 'Terminated'
        /// </summary>
        [Test]
        public void TerminatedTest()
        {
            // TODO unit test for the property 'Terminated'
        }
        /// <summary>
        /// Test the property 'Waiting'
        /// </summary>
        [Test]
        public void WaitingTest()
        {
            // TODO unit test for the property 'Waiting'
        }

    }

}
