/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1GitRepoVolumeSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1GitRepoVolumeSourceTests
    {
        // TODO uncomment below to declare an instance variable for V1GitRepoVolumeSource
        //private V1GitRepoVolumeSource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1GitRepoVolumeSource
            //instance = new V1GitRepoVolumeSource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1GitRepoVolumeSource
        /// </summary>
        [Test]
        public void V1GitRepoVolumeSourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1GitRepoVolumeSource
            //Assert.IsInstanceOfType<V1GitRepoVolumeSource> (instance, "variable 'instance' is a V1GitRepoVolumeSource");
        }

        /// <summary>
        /// Test the property 'Directory'
        /// </summary>
        [Test]
        public void DirectoryTest()
        {
            // TODO unit test for the property 'Directory'
        }
        /// <summary>
        /// Test the property 'Repository'
        /// </summary>
        [Test]
        public void RepositoryTest()
        {
            // TODO unit test for the property 'Repository'
        }
        /// <summary>
        /// Test the property 'Revision'
        /// </summary>
        [Test]
        public void RevisionTest()
        {
            // TODO unit test for the property 'Revision'
        }

    }

}
