/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1PodCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1PodConditionTests
    {
        // TODO uncomment below to declare an instance variable for V1PodCondition
        //private V1PodCondition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1PodCondition
            //instance = new V1PodCondition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1PodCondition
        /// </summary>
        [Test]
        public void V1PodConditionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1PodCondition
            //Assert.IsInstanceOfType<V1PodCondition> (instance, "variable 'instance' is a V1PodCondition");
        }

        /// <summary>
        /// Test the property 'LastProbeTime'
        /// </summary>
        [Test]
        public void LastProbeTimeTest()
        {
            // TODO unit test for the property 'LastProbeTime'
        }
        /// <summary>
        /// Test the property 'LastTransitionTime'
        /// </summary>
        [Test]
        public void LastTransitionTimeTest()
        {
            // TODO unit test for the property 'LastTransitionTime'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
