/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.7.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kubernetes.DotNet.Api;
using Kubernetes.DotNet.Model;
using Kubernetes.DotNet.Client;
using System.Reflection;

namespace Kubernetes.DotNet.Test
{
    /// <summary>
    ///  Class for testing V1ResourceRequirements
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V1ResourceRequirementsTests
    {
        // TODO uncomment below to declare an instance variable for V1ResourceRequirements
        //private V1ResourceRequirements instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1ResourceRequirements
            //instance = new V1ResourceRequirements();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1ResourceRequirements
        /// </summary>
        [Test]
        public void V1ResourceRequirementsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V1ResourceRequirements
            //Assert.IsInstanceOfType<V1ResourceRequirements> (instance, "variable 'instance' is a V1ResourceRequirements");
        }

        /// <summary>
        /// Test the property 'Limits'
        /// </summary>
        [Test]
        public void LimitsTest()
        {
            // TODO unit test for the property 'Limits'
        }
        /// <summary>
        /// Test the property 'Requests'
        /// </summary>
        [Test]
        public void RequestsTest()
        {
            // TODO unit test for the property 'Requests'
        }

    }

}
